###########################################################
# Makefile generated by xIDE for uEnergy                   
#                                                          
# Project: csr_mesh_switch_csr102x
# Configuration: Release
# Generated: ÖÜ¶þ ÁùÔÂ 5 09:53:55 2018
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

XIDE_PROJECT=csr_mesh_switch_csr102x
XIDE_CONFIG=Release
OUTPUT=csr_mesh_switch_csr102x
OUTDIR=C:/Users/Administrator/Desktop/CSR/csrmesh_2.1v_node_applications_A05/CSRmesh_2_1_v_Node/applications/csr_mesh_switch
DEFS=-DSERVER -DPERIPHERAL -DOBSERVER -DNVM_DONT_PAD 

LIBRARY_VERSION=CSR102x_A05
MTP_STATUS=Auto
PROJ_DRAM_MODEL=DRAM_16KB
OUTPUT_TYPE=EXECUTABLE
BUILD_TYPE=RELEASE
PROJ_BUILT_FOR=FLASH
PROJ_STORE_ID=1
PROJ_STORE_MODEL=STORE_MODEL_CUSTOM
PROJ_STORE_CONFIG_FILE=app_store_config_smem_a.stores
ERASE_SMEM=TRUE
ERASE_MTP=TRUE
PROJ_CS_FILE=csr_mesh_switch_csr102x.htfp
MASTER_DB=app_gatt_db.db
LIBPATHS=..\mesh_common\mesh\libraries\$(LIBRARY_VERSION)
INCPATHS=..\mesh_common\...
PROJ_INCLUDE_FILE=
STRIP_SYMBOLS=FALSE
PROJ_SECURITY=NO_SECURITY
PROJ_SIGNATURE_PRIVATE_KEY_FILE=
PROJ_SIGNATURE_PUBLIC_KEY_FILE=
PROJ_ENCRYPTION_KEY_FILE=
SPI_LOCK_KEY_FILE=
ENABLE_GAIA_OTAU=TRUE
PROJ_UPD_FILE=mesh_release_$(LIBRARY_VERSION).upd

LIBS=csrmesh light_client power_client switch_server extension_server extension_client time_client time_server action_server watchdog_server ping_server attention_server data_server data_client battery_server largeobjecttransfer_server 
DBS=\
\
      ../mesh_common/server/gap/gap_service_db.db\
      ../mesh_common/server/gatt/gatt_service_db.db\
      ../mesh_common/server/mesh_control/mesh_control_service_db.db\
      ../mesh_common/server/gaia/gaia_db.db\
      app_gatt_db.db

INPUTS=\
      ../mesh_common/peripheral/conn_param_update.c\
      ../mesh_common/components/nvm_manager/nvm_access.c\
      ../mesh_common/components/connection_manager/cm_common.c\
      ../mesh_common/components/connection_manager/cm_hal.c\
      ../mesh_common/components/connection_manager/cm_private.c\
      ../mesh_common/components/connection_manager/cm_security.c\
      ../mesh_common/components/connection_manager/cm_server.c\
      ../mesh_common/components/connection_manager/cm_observer.c\
      ../mesh_common/components/connection_manager/cm_peripheral.c\
      ../mesh_common/mesh/drivers/battery_hw.c\
      ../mesh_common/mesh/drivers/iot_hw.c\
      ../mesh_common/mesh/drivers/csr_mesh_ps_ifce.c\
      ../mesh_common/mesh/handlers/attention_model/attention_model_handler.c\
      ../mesh_common/mesh/handlers/battery_model/battery_model_handler.c\
      ../mesh_common/mesh/handlers/core_mesh/core_mesh_handler.c\
      ../mesh_common/mesh/handlers/data_model/data_model_handler.c\
      ../mesh_common/mesh/handlers/watchdog_model/watchdog_model_handler.c\
      ../mesh_common/mesh/handlers/common/app_util.c\
      ../mesh_common/mesh/handlers/connection/connection_handler.c\
      ../mesh_common/mesh/handlers/advertisement/advertisement_handler.c\
      ../mesh_common/mesh/handlers/time_model/time_model_handler.c\
      ../mesh_common/mesh/handlers/action_model/action_model_handler.c\
      ../mesh_common/mesh/handlers/extension_model/extension_model_handler.c\
      ../mesh_common/mesh/handlers/largeobjecttransfer_model/largeobjecttransfer_model_handler.c\
      ../mesh_common/mesh/handlers/otau/app_otau_handler.c\
      ../mesh_common/server/gap/gap_service.c\
      ../mesh_common/server/gatt/gatt_service.c\
      ../mesh_common/server/mesh_control/mesh_control_service.c\
      ../mesh_common/server/gaia/byte_utils.c\
      ../mesh_common/server/gaia/gaia.c\
      ../mesh_common/server/gaia/gaia_otau.c\
      ../mesh_common/server/gaia/gaia_service.c\
      main_app.c\
      app_mesh_handler.c\
      app_hw.c\
      $(DBS)

HTF=

# Project-specific options
erase_nvm=1

-include csr_mesh_switch_csr102x.mak
include $(SDK)/genmakefile.uenergy
